import "./globals.css";

import Header from "../components/Header.jsx";

import ActiveSectionContextProvider from "../context/section-context.jsx";
import { Toaster } from "react-hot-toast";
import Footer from "../components/Footer.jsx";
import ThemeSwitch from "@/components/ThemeSwitch.jsx";
import ThemeContextProvider from "@/context/theme-context.jsx";

export const metadata = {
  title: "NextJS portfolio website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className="bg-gray-50 
                    dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90"
      >
        <div
          className="header-circle -top-[10rem] left-1/2 -translate-x-1/2 w-[85rem] h-[35rem]
                  from-blue-400 to-slate-900 blur-3xl opacity-30 -z-[100]
                  dark:bg-[#946263] dark:w-[40rem]"
        ></div>
        <div
          className="header-circle top-[3rem] right-[35rem] w-[40rem] h-[40rem] from-red-100 blur-3xl -z-[100]
                   dark:bg-[#534bac] dark:from-gray-900 dark:to-gray-800 dark:right-[20rem] dark:w-[80rem] dark:h-[40rem]"
        ></div>

        <ThemeContextProvider>
          <ActiveSectionContextProvider>
            <Header />
            {children}
            <Footer />
            <Toaster position="bottom-left" />
            <ThemeSwitch />
          </ActiveSectionContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
